window.FRANCE_CONTENT = {
  squad: [
    {name:'Mike Maignan',position:'Gardien',club:'AC Milan'},
    {name:'Brice Samba',position:'Gardien',club:'Rennes'},
    {name:'Lucas Chevalier',position:'Gardien',club:'Lille'},
    {name:'William Saliba',position:'Défenseur',club:'Arsenal'},
    {name:'Ibrahima Konaté',position:'Défenseur',club:'Liverpool'},
    {name:'Dayot Upamecano',position:'Défenseur',club:'Bayern Munich'},
    {name:'Jules Koundé',position:'Défenseur',club:'Barcelona'},
    {name:'Theo Hernandez',position:'Défenseur',club:'AC Milan'},
    {name:'Lucas Hernandez',position:'Défenseur',club:'Paris Saint-Germain'},
    {name:'Benjamin Pavard',position:'Défenseur',club:'Inter Milan'},
    {name:'Jonathan Clauss',position:'Défenseur',club:'Nice'},
    {name:'Aurélien Tchouaméni',position:'Milieu',club:'Real Madrid'},
    {name:'Eduardo Camavinga',position:'Milieu',club:'Real Madrid'},
    {name:'Adrien Rabiot',position:'Milieu',club:'Marseille'},
    {name:'Warren Zaïre-Emery',position:'Milieu',club:'Paris Saint-Germain'},
    {name:'Youssouf Fofana',position:'Milieu',club:'AC Milan'},
    {name:'Kylian Mbappé',position:'Attaquant',club:'Real Madrid'},
    {name:'Ousmane Dembélé',position:'Attaquant',club:'Paris Saint-Germain'},
    {name:'Marcus Thuram',position:'Attaquant',club:'Inter Milan'},
    {name:'Randal Kolo Muani',position:'Attaquant',club:'Paris Saint-Germain'},
    {name:'Bradley Barcola',position:'Attaquant',club:'Paris Saint-Germain'},
    {name:'Michael Olise',position:'Attaquant',club:'Bayern Munich'},
    {name:'Kingsley Coman',position:'Attaquant',club:'Bayern Munich'}
  ],
  scorers: ['William Saliba','Ibrahima Konaté','Dayot Upamecano','Jules Koundé','Theo Hernandez','Benjamin Pavard','Aurélien Tchouaméni','Eduardo Camavinga','Adrien Rabiot','Warren Zaïre-Emery','Youssouf Fofana','Kylian Mbappé','Ousmane Dembélé','Marcus Thuram','Randal Kolo Muani','Bradley Barcola','Michael Olise','Kingsley Coman'],
  recentForm: ['W','W','W','W','W'],
  quotes: [
    {text:'Le football se joue avec la tête. Les pieds ne sont que les outils.',by:'Andrea Pirlo'},
    {text:'Plus la victoire est difficile, plus le bonheur de gagner est grand.',by:'Pelé'},
    {text:'Il faut se battre pour atteindre son rêve, faire des sacrifices et travailler dur.',by:'Lionel Messi'},
    {text:'J’en veux toujours plus. Qu’il s’agisse d’un but ou d’une victoire, je ne suis jamais satisfait.',by:'Kylian Mbappé'},
    {text:'Un champion a peur de perdre. Tous les autres ont peur de gagner.',by:'Billie Jean King'}
  ],
  spotlightFacts: {
    'Kylian Mbappé':['Capitaine de la France et l’un des meilleurs buteurs de l’histoire des Bleus.','Champion du monde en 2018 alors qu’il était encore adolescent.','Auteur d’un triplé en finale de la Coupe du monde 2022.'],
    'Ousmane Dembélé':['Ailier ambidextre réputé pour son accélération et sa créativité.','Champion du monde 2018 avec la France.','Peut jouer sur les deux ailes ou dans l’axe.'],
    'Aurélien Tchouaméni':['Milieu défensif apprécié pour son placement et sa récupération du ballon.','Buteur contre l’Angleterre en quart de finale de la Coupe du monde 2022.','Peut également jouer en défense centrale.'],
    'William Saliba':['Défenseur central calme, rapide et à l’aise dans la relance.','S’est imposé comme titulaire régulier chez les Bleus dans les années 2020.','Réputé pour ses duels et ses montées balle au pied.']
  },
  facts: [
    'La France a remporté la Coupe du monde masculine en 1998 et 2018.',
    'La France a disputé quatre finales de Coupe du monde masculine entre 1998 et 2022.',
    'Didier Deschamps a gagné la Coupe du monde comme capitaine en 1998 puis comme sélectionneur en 2018.',
    'Zinédine Zidane a marqué deux buts en finale de la Coupe du monde 1998.',
    'Kylian Mbappé a marqué en finale de la Coupe du monde 2018 à 19 ans.',
    'Just Fontaine a inscrit le record de 13 buts lors de la Coupe du monde 1958.',
    'La France a remporté le Championnat d’Europe en 1984 et 2000.',
    'Michel Platini a marqué neuf buts à l’Euro 1984.',
    'La France a remporté les Coupes des confédérations 2001 et 2003.',
    'Le Stade de France a accueilli la finale de la Coupe du monde 1998.',
    'Le premier match international masculin de la France a eu lieu en 1904.',
    'Raymond Kopa a remporté le Ballon d’Or en 1958.',
    'Jean-Pierre Papin a remporté le Ballon d’Or en 1991.',
    'La France a battu le Brésil 3-0 en finale de la Coupe du monde 1998.',
    'La France a battu la Croatie 4-2 en finale de la Coupe du monde 2018.',
    'Antoine Griezmann a remporté le Soulier d’or de l’Euro 2016.',
    'Hugo Lloris était capitaine lors du titre mondial de 2018.',
    'La France a atteint la finale de 2006 après avoir battu le Portugal en demi-finale.',
    'Lilian Thuram a marqué les deux buts français en demi-finale de la Coupe du monde 1998 contre la Croatie.',
    'La France a remporté la Ligue des nations de l’UEFA en 2021.'
  ]
};
window.ENGLAND_CONTENT = window.FRANCE_CONTENT;
