document.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id); let lang=localStorage.getItem('france_lang')||'en';
 const dictionary={
  en:{toggle:'FR',stage:'Semi-final countdown',motto:'Every match. Every goal. Every step to the World Cup Final.',lead:'Countdown, team news, predictions, quiz and France’s route to the final.',road:'Road',news:'Team News',quiz:'Quiz',poll:'Poll',players:'Players',predictor:'Predictor'},
  fr:{toggle:'EN',stage:'Compte à rebours avant la demi-finale',motto:'Chaque match. Chaque but. Chaque étape vers la finale de la Coupe du monde.',lead:'Compte à rebours, actualités, pronostics, quiz et parcours de la France vers la finale.',road:'Parcours',news:'Actualités',quiz:'Quiz',poll:'Sondage',players:'Joueurs',predictor:'Pronostic'}
 };
 function applyLanguage(){const d=dictionary[lang]; document.documentElement.lang=lang; if($('languageToggle'))$('languageToggle').textContent=d.toggle; if($('heroStage'))$('heroStage').textContent=d.stage; document.querySelector('.motto')&&(document.querySelector('.motto').textContent=d.motto); document.querySelector('.hero-copy .lead')&&(document.querySelector('.hero-copy .lead').textContent=d.lead); const links=[...document.querySelectorAll('#navLinks a')]; [d.road,d.news,d.quiz,d.poll,d.players,d.predictor].forEach((x,i)=>links[i]&&(links[i].textContent=x)); localStorage.setItem('france_lang',lang)}
 $('languageToggle')?.addEventListener('click',()=>{lang=lang==='en'?'fr':'en';applyLanguage()}); applyLanguage();
 const messages=['Allez les Bleus! Toute la France est derrière vous.','Unis sous le même drapeau. Faites-nous rêver!','Le 14 juillet, tous en bleu. Direction la finale!','Fiers de nos Bleus. Donnez tout contre l’Espagne!','Deux étoiles sur le maillot, une troisième dans nos rêves.','Ensemble jusqu’au bout. Allez la France!'];
 $('generateMessage')?.addEventListener('click',()=>{$('fanMessage').textContent=messages[Math.floor(Math.random()*messages.length)]});
 $('copyMessage')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('fanMessage').textContent);$('copyMessage').textContent='Copied';setTimeout(()=>$('copyMessage').textContent='Copy message',1200)}catch(e){}});
 function updateCard(){const fs=$('engScore')?.value||2, ss=$('norScore')?.value||1, scorer=$('firstScorer')?.value||'Kylian Mbappé'; $('cardFranceScore').textContent=fs;$('cardSpainScore').textContent=ss;$('cardScorer').textContent='First France scorer: '+scorer}
 $('updateShareCard')?.addEventListener('click',updateCard); updateCard();
 $('downloadShareCard')?.addEventListener('click',()=>{const fs=$('cardFranceScore').textContent,ss=$('cardSpainScore').textContent,sc=$('cardScorer').textContent; const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#002395"/><stop offset=".5" stop-color="#fff"/><stop offset="1" stop-color="#ed2939"/></linearGradient></defs><rect width="1200" height="630" fill="#07152f"/><rect x="40" y="40" width="1120" height="550" rx="40" fill="url(#g)" opacity=".22"/><text x="600" y="130" text-anchor="middle" fill="#fff" font-family="Arial" font-size="34" font-weight="700">WORLD CUP SEMI-FINAL · 14 JULY 2026</text><text x="600" y="310" text-anchor="middle" fill="#fff" font-family="Arial" font-size="86" font-weight="900">FRANCE ${fs}–${ss} SPAIN</text><text x="600" y="400" text-anchor="middle" fill="#fff" font-family="Arial" font-size="34">${sc}</text><text x="600" y="510" text-anchor="middle" fill="#fff" font-family="Arial" font-size="48" font-weight="900">ALLEZ LES BLEUS 🇫🇷</text></svg>`; const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download='france-spain-prediction.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
});