document.addEventListener('DOMContentLoaded', () => {
  const $ = id => document.getElementById(id);
  let lang = localStorage.getItem('france_lang') || 'en';

  const fr = new Map(Object.entries({
    'Skip to content':'Aller au contenu','Loading matchday...':'Chargement du jour de match…','Menu':'Menu','Road':'Parcours','Team News':'Actualités','Poll':'Sondage','Players':'Joueurs','Predictor':'Pronostic',
    'Semi-final countdown':'Compte à rebours avant la demi-finale','Every match. Every goal. Every step to the World Cup Final.':'Chaque match. Chaque but. Chaque étape vers la finale de la Coupe du monde.','Countdown, team news, predictions, quiz and France’s route to the final.':'Compte à rebours, actualités, pronostics, quiz et parcours de la France vers la finale.',
    '⚽ World Cup semi-final':'⚽ Demi-finale de la Coupe du monde','📅 14 July 2026':'📅 14 juillet 2026','🏟️ Dallas Stadium, Arlington':'🏟️ Stade de Dallas, Arlington','days':'jours','hours':'heures','mins':'min','secs':'sec','Kick-off time loading...':'Chargement de l’heure du coup d’envoi…',
    'Match day':'Jour de match','Countdown':'Compte à rebours','Next match':'Prochain match','Progress':'Parcours','Semi-final stage':'Demi-finale','⭐ Player spotlight':'⭐ Joueur à la une','Show another player':'Voir un autre joueur','📈 Recent form':'📈 Forme récente','France’s last five':'Les cinq derniers matches de la France','Most recent match shown first.':'Le match le plus récent apparaît en premier.','🕒 Kick-off times':'🕒 Horaires du match','Match time':'Heure du match','Your local time':'Votre heure locale','United Kingdom':'Royaume-Uni','Belgium':'Belgique',
    '14 July special':'Spécial 14 juillet','Bastille Day semi-final':'Demi-finale du 14 juillet','France face Spain on the national day. Allez les Bleus!':'La France affronte l’Espagne le jour de la fête nationale. Allez les Bleus !',
    'French football history':'Histoire du football français','Two stars, unforgettable moments':'Deux étoiles, des moments inoubliables','France’s landmark World Cup achievements.':'Les grands moments de la France en Coupe du monde.','World champions on home soil':'Champions du monde à domicile','France beat Brazil 3–0 in the final in Saint-Denis.':'La France bat le Brésil 3-0 en finale à Saint-Denis.','World Cup finalists':'Finalistes de la Coupe du monde','Les Bleus reached the final in Germany.':'Les Bleus atteignent la finale en Allemagne.','World champions in Russia':'Champions du monde en Russie','France beat Croatia 4–2 to lift their second World Cup.':'La France bat la Croatie 4-2 et remporte sa deuxième Coupe du monde.','Finalists again':'De nouveau finalistes','France reached a second consecutive final.':'La France atteint une deuxième finale consécutive.',
    'Golden Boot tracker':'Course au Soulier d’or','France top scorers':'Meilleurs buteurs français','8 goals':'8 buts','5 goals':'5 buts','0 goals':'0 but','Figures checked on 13 July 2026.':'Chiffres vérifiés le 13 juillet 2026.','Watch in France':'Regarder en France','French TV information':'Diffusion TV en France','The match is available through official French World Cup broadcasters. Check the programme guide shortly before kick-off.':'Le match est diffusé par les diffuseurs officiels français de la Coupe du monde. Consultez le programme peu avant le coup d’envoi.',
    'Support Les Bleus':'Soutenez les Bleus','Allez les Bleus message generator':'Générateur de message Allez les Bleus','Create a short matchday message to copy and share.':'Créez un court message à copier et à partager.','New message':'Nouveau message','Copy message':'Copier le message',
    'Player comparison':'Comparaison de joueurs','Mbappé v Lamine Yamal':'Mbappé face à Lamine Yamal','Two match-winners, two different styles.':'Deux joueurs décisifs, deux styles différents.','Forward':'Attaquant','Winger':'Ailier','Tournament goals':'Buts dans le tournoi','Strength':'Point fort','Pace and finishing':'Vitesse et finition','Creativity and dribbling':'Créativité et dribble','World Cup titles':'Titres mondiaux',
    'Share your prediction':'Partagez votre pronostic','Match prediction card':'Carte de pronostic','Generate a clean card for WhatsApp or social media.':'Créez une carte à partager sur WhatsApp ou les réseaux sociaux.','First France scorer: Kylian Mbappé':'Premier buteur français : Kylian Mbappé','Update from predictor':'Mettre à jour depuis le pronostic','Download card':'Télécharger la carte',
    'Tournament path':'Parcours du tournoi','France’s Road to the Final':'Le parcours de la France vers la finale','Follow France’s men through the World Cup knockout route.':'Suivez le parcours des Bleus dans la phase à élimination directe.','Predicted XI':'Onze probable','Latest semi-final notes for France supporters.':'Les dernières informations avant la demi-finale.','Unofficial fan notes. Check official team channels for confirmed line-ups.':'Informations non officielles. Consultez les canaux officiels pour les compositions confirmées.',
    '🇪🇸 Semi-final opposition':'🇪🇸 Adversaire en demi-finale','Spain at a glance':'L’Espagne en bref','Five quick facts before the World Cup semi-final.':'Quelques repères avant la demi-finale.','Key figure':'Point fort','Spain combine technical midfield play with dangerous wide attackers.':'L’Espagne associe un milieu technique à des ailiers dangereux.','Quarter-final':'Quart de finale','Spain beat Belgium 2–1 in the quarter-final.':'L’Espagne a battu la Belgique 2-1 en quart de finale.','Style':'Style','Patient possession, clever movement and ruthless transitions.':'Possession patiente, déplacements intelligents et transitions rapides.','World Cup history':'Histoire en Coupe du monde','France and Spain have met regularly in major tournaments, including the 1984 European Championship final and the 2021 Nations League final.':'La France et l’Espagne se sont souvent affrontées dans les grandes compétitions, notamment en finale de l’Euro 1984 et de la Ligue des nations 2021.',
    'World Cup quiz':'Quiz Coupe du monde','Five-question France challenge':'Défi France en cinq questions','Five random medium and hard questions from a carefully checked question bank.':'Cinq questions aléatoires de niveau moyen ou difficile, tirées d’une sélection vérifiée.','Check answers':'Vérifier les réponses','Play 5 new questions':'Cinq nouvelles questions','Current streak:':'Série actuelle :','Best score:':'Meilleur score :',
    'Fan poll':'Sondage des supporters','How far will France go?':'Jusqu’où ira la France ?','Vote once on this device and see the local fan mood. Lightweight, private and perfect for mobile.':'Votez sur cet appareil et découvrez la tendance des supporters. Simple, privé et adapté au mobile.','Semi-final exit':'Élimination en demi-finale','Runner-up':'Finaliste','World Cup winners 🏆':'Champions du monde 🏆',
    'Confidence meter':'Indice de confiance','How confident are you France will beat Spain?':'À quel point pensez-vous que la France battra l’Espagne ?','Slide it, save it and compare your matchday mood.':'Déplacez le curseur et enregistrez votre niveau de confiance.','Strong belief':'Très confiant','Save confidence':'Enregistrer','Reset':'Réinitialiser',
    'Match prediction':'Pronostic du match','Score Predictor':'Pronostic du score','Pick any score and the first France goalscorer.':'Choisissez le score et le premier buteur français.','France goals':'Buts de la France','Spain goals':'Buts de l’Espagne','First France scorer':'Premier buteur français','Player of the match':'Joueur du match','France corners':'Corners de la France','France clean sheet':'La France sans encaisser','Yes':'Oui','No':'Non','Save prediction':'Enregistrer le pronostic','Copy prediction':'Copier le pronostic','Make your prediction above.':'Faites votre pronostic ci-dessus.',
    'Did you know?':'Le saviez-vous ?','France World Cup Fact':'Une anecdote sur la France','Show another fact':'Une autre anecdote','💬 Matchday quote':'💬 Citation du jour','Another quote':'Une autre citation','🎉 Celebration mode':'🎉 Mode célébration','France win?':'Victoire de la France ?','Launch a full-screen silent stadium celebration.':'Lancez une célébration plein écran et silencieuse.','Celebrate a France win':'Célébrer une victoire française',
    '🌤 Stadium weather':'🌤 Météo au stade','Dallas match weather':'Météo du match à Dallas','Loading match-day weather…':'Chargement de la météo…','📅 Next France fixtures':'📅 Prochains matches de la France','🏆 France’s route':'🏆 Parcours de la France','Two wins from history':'À deux victoires de l’histoire','A simple path from the quarter-final victory to the World Cup final.':'Le chemin du quart de finale jusqu’à la finale.','France reached the semi-final with a 2–0 win over Morocco.':'La France a atteint la demi-finale en battant le Maroc 2-0.','Kick-off 21:00 France, 14:00 local time.':'Coup d’envoi à 21 h en France, 14 h heure locale.','France qualify by beating Spain.':'La France se qualifiera en battant l’Espagne.',
    'Official and live coverage':'Informations officielles et suivi en direct','Useful links':'Liens utiles','Trusted places for confirmed squads, tournament information, scores and match coverage.':'Sources fiables pour les équipes, le tournoi, les scores et le suivi du match.','FIFA World Cup':'Coupe du monde de la FIFA','Built by Richard Freedman for the fans, including muppets. Unofficial France men’s World Cup fan site.':'Créé par Richard Freedman pour les supporters, y compris les guignols. Site non officiel consacré aux Bleus.','Privacy':'Confidentialité','Cookies':'Cookies','Contact':'Contact','FRANCE WIN!':'VICTOIRE DE LA FRANCE !','Les Bleus roar on.':'Les Bleus poursuivent leur route.','Close celebration':'Fermer','This site uses local storage to remember your prediction and cookie choice.':'Ce site utilise le stockage local pour mémoriser votre pronostic et votre choix concernant les cookies.',"France attacking players":"Joueurs offensifs français","Players to watch":"Joueurs à suivre","Captain":"Capitaine","No unverified tournament goal totals are shown.":"Aucun total de buts non vérifié n’est affiché.","Role":"Rôle","Captain and forward":"Capitaine et attaquant","Five random medium and hard questions from a carefully checked question bank. Play again for a fresh set.":"Cinq questions aléatoires de niveau moyen ou difficile, issues d’une sélection soigneusement vérifiée. Rejouez pour obtenir une nouvelle série.","Quiz loading problem. Please refresh the page.":"Problème de chargement du quiz. Veuillez actualiser la page.","Medium":"Moyen","Hard":"Difficile","You answered":"Vous avez répondu à","Unanswered questions count as incorrect.":"Les questions sans réponse sont considérées comme incorrectes.","Explanations are now shown.":"Les explications sont maintenant affichées.","Subject to France progressing":"Sous réserve de qualification de la France","Future fixtures will appear here when confirmed.":"Les prochains matches apparaîtront ici après confirmation.","Clear":"Ciel dégagé","Mainly clear":"Globalement dégagé","Partly cloudy":"Partiellement nuageux","Overcast":"Couvert","Foggy":"Brouillard","Light drizzle":"Faible bruine","Rain":"Pluie","Moderate rain":"Pluie modérée","Heavy rain":"Forte pluie","Rain showers":"Averses","Thunderstorms":"Orages","Forecast available":"Prévisions disponibles","high":"maximum","Low":"Minimum","Wind":"Vent","Forecast for":"Prévisions pour","Weather can change.":"La météo peut évoluer.","Live weather is temporarily unavailable.":"La météo en direct est temporairement indisponible.","Check weather":"Voir la météo","Copied":"Copié","Prediction copied.":"Pronostic copié."
  }));

  const enOriginal = new WeakMap();
  const translateText = text => {
    const lead=text.match(/^(\s*)(.*?)(\s*)$/s); if(!lead) return text;
    const core=lead[2]; return lead[1]+(fr.get(core)||core)+lead[3];
  };
  function walk(root=document.body){
    const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement && !['SCRIPT','STYLE'].includes(n.parentElement.tagName) && n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});
    const nodes=[]; while(w.nextNode()) nodes.push(w.currentNode);
    nodes.forEach(n=>{ if(!enOriginal.has(n)) enOriginal.set(n,n.nodeValue); n.nodeValue=lang==='fr'?translateText(enOriginal.get(n)):enOriginal.get(n); });
  }
  function applyLanguage(){
    document.documentElement.lang=lang;
    const toggle=$('languageToggle'); if(toggle){toggle.textContent=lang==='en'?'🇫🇷 FRANÇAIS':'🇬🇧 ENGLISH'; toggle.setAttribute('aria-label',lang==='en'?'Afficher le site en français':'Show site in English');}
    walk(); localStorage.setItem('france_lang',lang);
  }
  $('languageToggle')?.addEventListener('click',()=>{lang=lang==='en'?'fr':'en';localStorage.setItem('france_lang',lang);location.reload();});
  const observer=new MutationObserver(muts=>{if(lang!=='fr')return; muts.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)walk(n); else if(n.nodeType===3&&n.nodeValue.trim()){if(!enOriginal.has(n))enOriginal.set(n,n.nodeValue);n.nodeValue=translateText(enOriginal.get(n));}}));});
  observer.observe(document.body,{childList:true,subtree:true});

  const messages=['Allez les Bleus ! Toute la France est derrière vous.','Unis sous le même drapeau. Faites-nous rêver !','Le 14 juillet, tous en bleu. Direction la finale !','Fiers de nos Bleus. Donnez tout contre l’Espagne !','Deux étoiles sur le maillot, une troisième dans nos rêves.','Ensemble jusqu’au bout. Allez la France !'];
  $('generateMessage')?.addEventListener('click',()=>{$('fanMessage').textContent=messages[Math.floor(Math.random()*messages.length)];});
  $('copyMessage')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('fanMessage').textContent);$('copyMessage').textContent=lang==='fr'?'Copié':'Copied';setTimeout(()=>applyLanguage(),1200);}catch{}});
  function updateCard(){const fs=$('engScore')?.value||2,ss=$('norScore')?.value||1,scorer=$('firstScorer')?.value||'Kylian Mbappé';$('cardFranceScore').textContent=fs;$('cardSpainScore').textContent=ss;$('cardScorer').textContent=(lang==='fr'?'Premier buteur français : ':'First France scorer: ')+scorer;}
  $('updateShareCard')?.addEventListener('click',updateCard); updateCard();
  $('downloadShareCard')?.addEventListener('click',()=>{const fs=$('cardFranceScore').textContent,ss=$('cardSpainScore').textContent,sc=$('cardScorer').textContent;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#07152f"/><text x="600" y="130" text-anchor="middle" fill="white" font-family="Arial" font-size="34" font-weight="700">COUPE DU MONDE · DEMI-FINALE · 14 JUILLET 2026</text><text x="600" y="310" text-anchor="middle" fill="white" font-family="Arial" font-size="86" font-weight="900">FRANCE ${fs}–${ss} ESPAGNE</text><text x="600" y="400" text-anchor="middle" fill="white" font-family="Arial" font-size="34">${sc}</text><text x="600" y="510" text-anchor="middle" fill="white" font-family="Arial" font-size="48" font-weight="900">ALLEZ LES BLEUS 🇫🇷</text></svg>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download='pronostic-france-espagne.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
  setTimeout(applyLanguage,150);
});
